name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add the configure-pages action with the enablement parameter
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
        with:
          enablement: 'true'  # This will enable GitHub Pages if it's not already enabled

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.3.0
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpx pkg-pr-new publish
