name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # Install pnpm directly using npm
      - name: Install pnpm
        run: npm install -g pnpm

      # Ensure pnpm is in the PATH
      - name: Add pnpm to PATH
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - run: pnpx pkg-pr-new publish
