name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Bun
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      # Add Bun to PATH
      - name: Set up PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Build the project
      - name: Build
        run: bun build

      # Publish the project
      - run: bun pkg-pr-new publish
